### ISSUE TITLE
Question about Item List for Wired Only

### ISSUE THREAD

**Issue by KevinFlummi** [tadfisher/nyx-kb#19]
Hi, I intend to build this keyboard, but don't need any wireless function, so I wanted to ask if that means that I could just not use the slide switches because the keyboard is only on when connected with usb?
And also, just for clarity, are the PTS636SM25SMTRLFS switches intended as reset switches? If so, I would also plan on not using them, so that I can make a cleaner case and save 20 bucks on shipping costs.

**Comment by aleh-rymasheuski** [comment]
@yourbro17, your understanding is correct, the slide switches are only required to break the circuit with the batteries. No batteries - no use for the slide switches.

The PTS636SM25SMTRLFS are the reset switches. You can live without them if you don't mind resetting the controllers with a piece of wire when initially flashing the keyboard and using the [reset behaviors](https://zmk.dev/docs/behaviors/reset) in ZMK after. I don't have these switches and have used the keyboard for over a year now.

**Comment by KevinFlummi** [comment]
Alright thanks. I guess I will still use the sockets if I ever feel the need to switch to battery powered.
