### ISSUE TITLE
Question about configation of propertied on JLCPCB

### ISSUE THREAD

**Issue by grafanaKibana** [tadfisher/nyx-kb#7]
Hi, a am interested to produce pcb on JLCPCB as you recomended but i confuced with number of configurations, what is correct config here  here?
![image](https://user-images.githubusercontent.com/45916288/151701381-4da9e816-0865-4393-a1ab-135bb6efde89.png)

**Comment by wren** [comment]
If you use the default options on JLCPCB, and upload the gerber zip file (https://github.com/tadfisher/nyx-kb/blob/main/pcb/gerbers/nyx.zip), it will automatically update the correct options for you. After that, you can optionally change the color and surface finish, and you'll be ready to go.

I just had a batch of these printed up a few weeks ago doing this, and they came out great.
 
<img width="884" alt="PCB_Order___Online_PCB_Quote___SMT_Assembly_Quote_-_JLCPCB" src="https://user-images.githubusercontent.com/9453067/151714604-ed4d19a5-7e2f-4c76-bf11-7356eef96131.png">

**Comment by tadfisher** [comment]
Yep, mine were done in black-on-black with the ENIG finish, but there's nothing that requires heavier copper, castellation or whatnot.

I'd love to see your finished work! Glad to know someone else likes this board enough to build one.

**Comment by grafanaKibana** [comment]
Thank you guys very much!
