### ISSUE TITLE
What are the caps used in your build?

### ISSUE THREAD

**Issue by aleh-rymasheuski** [tadfisher/nyx-kb#8]
The build instructions are very detailed and list every part used in the build except the key caps. I assumed that some generic Kailh Choc key caps from Aliexpress would fit, but sadly enough, the 2u pieces didn't as they are a bit longer than the PCB allows.

Dimensions:
- 1u: 18x17 mm
- 2u: 34x17 mm

![caps](https://user-images.githubusercontent.com/9883236/151789497-a7854abf-03cf-4232-b6c1-2310e00e934c.png)

UPD: now I can see that the board design lists the lower switches as "1.5u" packages. This would have been a valuable piece of the docs. :)

**Comment by tadfisher** [comment]
The keycaps I'm using are MBK (seen here: https://mkultra.click/mbk-choc-keycaps). The dimensions are:

- 1u: 17.5x16.5mm
- 1.5u: 26.5x16.5mm
- 2u: 35.5x16.5mm

I will add the keycap requirements to the BOM, thanks for catching this.
